name: Matrix-Multiplication CI

on: [ push, pull_request ]

concurrency:
  group: '${{ github.event_name }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MPI
        id: mpi-setup
        uses: mpi4py/setup-mpi@v1

      - name: Setup CMake
        id: cmake-setup
        uses: jwlawson/actions-setup-cmake@v2
      - name: Configure CMake
        id: cmake-configuration
        run: cmake -S . -B build

      - name: Build
        id: build
        run: cmake --build build

      # Write test logs into test.log file
      - name: Run Tests
        id: unit-tests
        run: ctest --test-dir build --output-on-failure --output-log test.log

      # Analyze test.log to retrieve all the discovered errors
      # Write the discovered errors in test-report.log
      - name: Analyze test logs
        id: unit-tests-log-analysis
        if: always()
        run: grep -e 'Error [0-9]*' test.log | sort -u > test-report.log && cat test-report.log

      - name: Upload test logs analysis
        id: unit-tests-report-upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report.log
          path: test-report.log
          if-no-files-found: error
          retention-days: 10