name: Matrix-Multiplication CI

on: [ push, pull_request ]

concurrency:
  group: '${{ github.event_name }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: ctest --test-dir build